### ISSUE TITLE
Problem with frozen array on modular-scale gem

### ISSUE THREAD

**Issue by joelchristopher** [GumbyFramework/Gumby#183]
I am just testing out Gumby on Mac OS X dev environment.
Trying to run command:
compass watch and getting returned this error:

RuntimeError on line ["122"] of /Users/myuser/Projects/projectdir/sass/extensions/modular-scale/lib/modular-scale.rb: can't modify frozen Array

I also installed the ruby gem locally and updating config.rb but that returns the same result.
Any ideas?

**Comment by tamarmot** [comment]
Unfortunately I am having the same problem, but I am trying to use django-pipeline-compass to compile.  It seems that django-pipeline-compass includes an incomaptible version of compass.  I can't be the first one to use django pipeline to compile gumby, how has this problem been solved?  Thanks.

**Comment by timbo61** [comment]
Thank you tlimited. It's taken me ALL day to get to this point but your suggested version worked a treat!

**Comment by sneppa** [comment]
@ARolek, thanks, you saved me a lot of time! 
Works perfect with this versions:
rvm (1.11.3.9)
compass (0.12.6)
modular-scale (1.0.6)
sass (3.2.19)
sassy-math (1.5.1)

**Comment by micschk** [comment]
As the web is moving on, the gems installed are likely newer thatn those required by Gumby. I have good results by installing the older ones side by side, and then specifying which version of compass to use:

Install commands:
```
sudo gem install modular-scale -v 1.0.6
sudo gem install sass -v 3.2.19
sudo gem install compass -v 0.12.6"
```

And use compass 0.12.6:
```
%> compass _0.12.6_ watch
```
