### ISSUE TITLE
Can't compile SCSS with latest SASS and Compass releases.

### ISSUE THREAD

**Issue by Phunky** [GumbyFramework/Gumby#217]
Get the following when attempting to compile Gumby with local installed gems, running

λcompass watch
NameError on line ["2087"] of /usr/local/Cellar/ruby/2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb: uninitialized constant Gem::ConflictError
Run with --trace to see the full backtrace

My local gems installed are:

**\* LOCAL GEMS ***

bigdecimal (1.2.5, 1.2.4, 1.2.3)
breakpoint (2.4.2)
celluloid (0.15.2)
celluloid-io (0.15.0)
chunky_png (1.3.0, 1.2.9)
compass (1.0.0.alpha.19, 1.0.0.alpha.18, 0.12.4, 0.12.3, 0.12.2)
compass-core (1.0.0.alpha.19, 1.0.0.alpha.17)
compass-import-once (1.0.4, 1.0.2)
ffi (1.9.3)
fssm (0.2.10)
hitimes (1.2.1)
io-console (0.4.2)
json (1.8.1)
listen (2.7.1, 2.7.0, 1.1.6)
minitest (5.3.2, 5.3.0, 4.7.5)
modular-scale (1.0.6)
multi_json (1.9.2, 1.9.0)
nio4r (1.0.0)
psych (2.0.5, 2.0.4, 2.0.3, 2.0.2)
rake (10.2.2, 10.1.1, 10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rb-kqueue (0.2.2, 0.2.0)
rdoc (4.1.1, 4.1.0)
rubygems-update (2.2.2, 2.2.1)
sass (3.3.4, 3.3.0, 3.2.19, 3.2.14, 3.2.12)
sassy-maps (0.3.2)
sassy-math (1.5)
test-unit (2.5.5, 2.1.1.0, 2.1.0.0)
timers (2.0.0, 1.1.0)

This is on OSX 10.9 with everything managed via homebrew

**Comment by danhere** [comment]
Pull down the latest and try again. I updated to the latest modular-scale and tested myself with all the lastest versions of each gem.
