### ISSUE TITLE
Modular implementation of icon fonts

### ISSUE THREAD

**Issue by hazeltree** [GumbyFramework/Gumby#245]
Gumby at the present is extremely coupled with Entypo icon fonts. I'd like to discuss refactoring some of the code related to how icon font classes are generated to easily allow for alternate fonts and glyph lists. Are there any specific reasons the sass is so heavily tied to Entypo?

**Comment by danhere** [comment]
Gumby is really tightly married to Entypo, I agree. If you can figure out a way to make icons more modular, I'd be all ears to a pull request :)
