### ISSUE TITLE
update modular scale

### ISSUE THREAD

**Issue by abFx** [GumbyFramework/Gumby#256]
Gumby needs to update its modular scale dependency to new version.
Gumby can't be compile with latest compass/sass version because of incompatible units px and em.

After fixing this, people might now use gumby freely with bower and other frameworks such as ember-cli and broccoli-compass

**Comment by scottkellum** [comment]
I recently got an issue related to this on modular-scale: https://github.com/at-import/modular-scale/pull/85

Note that `incompatible units px and em` error is from Compass’ vertical rhythm module and Gumby must set the base size to a `px` value if it plans to use modular scale with Compass vertical rhythm regardless of what version is installed.

**Comment by abFx** [comment]
I upload an updated gumby version I saw somewhere, just make it available for other devs with similiar issues...  http://bower.io/search/?q=gumby-ember

**Comment by danhere** [comment]
If you guys can update modular scale and create a pull request I will merge it in asap. Thanks!

**Comment by danhere** [comment]
Newest modular-scale is now in Gumby. Pull down the latest and you should be all set.
