### ISSUE TITLE
File to import not found or unreadable: modular-scale. Rails 

### ISSUE THREAD

**Issue by jgrannas** [GumbyFramework/Gumby#257]
Trying to implement Gumby in Rails 4, and i am at a loss after two attempts and a few hours wasted. I dont want to just embed a compiled css file like a lot of the gumby-gems do, i want to be able to override scss defaults in my app.

So, I made a folder ***app/assets/stylesheets/base***
Then, ***app/assets/stylesheets/base/gumby*** contains the sass folder from the gumby git repo

In that base folder I placed a file: ***app/assets/stylesheets/base/base.scss*** which contains:
```
@import "gumby/gumby";
```

First i get:
```
File to import not found or unreadable: modular-scale.
```
Trying to figure out the issue, in the gumby.scss I changed:
```
@import "modular-scale"; TO @import "extensions/modular-scale/stylesheets/modular-scale";
```
Then I get:
```
Undefined variable: "$golden".
```

It would be really cool if you could put up a guide on how to integrate gumby into Rails & the asset pipeline. This was my first attempt at using a responsive framework... frustrated and sad :( .... going back to hand coding my responsive stuff.

Gemfile:
```
group :assets do
  gem 'compass-rails'
  gem 'modular-scale'
  gem 'sass-rails', '~> 4.0.3'
  gem 'uglifier', '>= 1.3.0'
  gem 'therubyracer', platforms: :ruby
end
```

**Comment by jgrannas** [comment]
I also tried using modular-scale ~> 1.0.6 to no avail.

**Comment by danhere** [comment]
This should be fixed now. I updated the bundled modular-scale to the latest within Gumby. If that doesn't work, read in the config.rb file on how to use the system gem rather than the bundled one.
