### ISSUE TITLE
Include modal dialogs

### ISSUE THREAD

**Issue by caouecs** [GumbyFramework/Gumby#26]
Hello,
I think Gumby needs modal dialog system to be complete, no ?

why not include a system like JQuery Modal (https://github.com/kylefox/jquery-modal)

**Comment by NandoSantana** [comment]
hi, have this problem, add requisition ajax, when a relation with id and next id on #modal11, so stoped feature. Observation = They works only in root html. I found transfering id relative for onclick buttom. Already have the solution? Post here my idea after resolved.
