### ISSUE TITLE
Gumby is overly difficult to add to an existing project.

### ISSUE THREAD

**Issue by traviswimer** [GumbyFramework/Gumby#260]
I tried out Gumby today, and I noticed that it is designed specifically for creating a new app. When you download the zip file of Gumby, what you get is basically a demo project. Although I think it is great that a demo project exists, it seems strange that it is used as THE Gumby source download.

Assume, for example, that someone has created a desktop web app that uses SASS. Then they decide to add mobile/responsive support using Gumby. The process one would take for this is:
  1. They download and unzip Gumby
  2. At this point they realize Gumby is a demo app, which means they need to move all their app's files into the Gumby folder. This of course means they would need to redo all the setup for their current app (grunt/gulp task, folder hierarchy, etc.).
  3. What they really want though is to simply insert Gumby into their current project, so instead they rummage through all the demo files and try to figure out what files are the actual framework.
  4. They decide to just copy the SASS folder over to their project so they can @import it from their own file.
  5. They run compass and get an error, and then spend a while Google-ing what ModularScale could possibly be and why Gumby is trying to import a file that doesn't exist (Not everyone is a Ruby expert).
  6. Eventually they figure out that they need to move the config.rb file to their top level directory. (Yay it works)
  7. Then a while later they want to add the Gumby Javascript library (which of course isn't in the `js` directory)
  8. They go use Bootstrap instead.

Hopefully my rambling has proved a point. With a very small amount of effort, Gumby could be a lot easier to setup. All it really needs is a download link that only includes the necessary framework files and a short explanation of how to add them into a project.

**Comment by danhere** [comment]
@traviswimer I agree Gumby should have been more modular overall, but hindsight is 20/20. I've updated Gumby to the latest modular-scale so you shouldn't run into any more issues with Compass. If you're having trouble with Ruby gems, let me know. I can try to assist.
