### ISSUE TITLE
HTTPS error visiting https://gumbyframework.com/

### ISSUE THREAD

**Issue by stuaxo** [GumbyFramework/Gumby#273]
Going to https://gumbyframework.com/ results in this:

![screenshot from 2017-10-25 16-11-07](https://user-images.githubusercontent.com/179677/32006610-2373f478-b99f-11e7-84c4-9ab2ea9a6909.png)

**Comment by danhere** [comment]
Our cert expired but we've sorted it out. Thanks for letting us know!

**Comment by stuaxo** [comment]
Great !  I only found it, because I was looking at the Gum theme in the Pelican Blog software.
