### ISSUE TITLE
$golden not assigned a value?

### ISSUE THREAD

**Issue by mrzeph** [GumbyFramework/Gumby#72]
Looking at _settings.scss at line 49, we see:

> $ratio: $golden !default; // Ratio for Modular Scale

I can find nowhere where $golden is assigned a value. Am I missing something? Should it be

> golden()    ?

**Comment by rprince** [comment]
This isn't reflected in the Gumby-master.zip linked from http://gumbyframework.com/

**Comment by danhere** [comment]
The latest modular-scale uses $golden and the settings file should reflect that. I just updated the tags and it should be included in the newest zip.
